services:
  todo-backend:
    image: ---orbuild---
    container_name: todo-backend
    restart: unless-stopped
    ports:
      - "80:3000"
    env_file:
      - .env
    networks:
      - todo-network

networks:
  todo-network:
    external: true
    name: ---todo-network-actual-name